const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:5000/api';
const request = async (path, token, options = {}) => { const response = await fetch(`${API_URL}${path}`, { headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}`, ...options.headers }, ...options }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.message || 'Request failed.'); return data; };
export const getCourses = (token) => request('/courses', token);
export const getMyCourses = (token) => request('/courses/mine', token);
export const getCourse = (id, token) => request(`/courses/${id}`, token);
export const createCourse = (values, token) => request('/courses', token, { method: 'POST', body: JSON.stringify(values) });
export const updateCourse = (id, values, token) => request(`/courses/${id}`, token, { method: 'PUT', body: JSON.stringify(values) });
export const deleteCourse = (id, token) => request(`/courses/${id}`, token, { method: 'DELETE' });
export const createModule = (courseId, values, token) => request(`/courses/${courseId}/modules`, token, { method: 'POST', body: JSON.stringify(values) });
export const updateModule = (id, values, token) => request(`/modules/${id}`, token, { method: 'PUT', body: JSON.stringify(values) });
export const deleteModule = (id, token) => request(`/modules/${id}`, token, { method: 'DELETE' });
export const createLecture = (moduleId, values, token) => request(`/modules/${moduleId}/lectures`, token, { method: 'POST', body: JSON.stringify(values) });
export const updateLecture = (id, values, token) => request(`/lectures/${id}`, token, { method: 'PUT', body: JSON.stringify(values) });
export const deleteLecture = (id, token) => request(`/lectures/${id}`, token, { method: 'DELETE' });
export const enrollCourse = (courseId, token) => request(`/enrollments/${courseId}`, token, { method: 'POST' });
export const getEnrollmentStatus = (courseId, token) => request(`/enrollments/${courseId}/status`, token);
export const getEnrolledCourses = (token) => request('/enrollments/my-courses', token);
export const unenrollCourse = (courseId, token) => request(`/enrollments/${courseId}`, token, { method: 'DELETE' });
export const getCourseProgress = (courseId, token) => request(`/progress/${courseId}`, token);
export const setLectureCompletion = (courseId, lectureId, completed, token) => request(`/progress/${courseId}/${lectureId}`, token, { method: 'PATCH', body: JSON.stringify({ completed }) });
