import Course from '../models/Course.js';
import Module from '../models/Module.js';
import Lecture from '../models/Lecture.js';
import Enrollment from '../models/Enrollment.js';
import Progress from '../models/Progress.js';
import { invalidId, isValidId } from '../utils/validation.js';

const counts = async (course) => { const modules = await Module.find({ course: course._id }).select('_id'); const lectureCount = modules.length ? await Lecture.countDocuments({ module: { $in: modules.map((item) => item._id) } }) : 0; return { ...course.toObject(), moduleCount: modules.length, lectureCount }; };
const owned = async (id, user, res) => { if (!isValidId(id)) { invalidId(res, 'course'); return null; } const course = await Course.findById(id); if (!course) { res.status(404).json({ message: 'Course not found.' }); return null; } if (course.faculty.toString() !== user.toString()) { res.status(403).json({ message: 'You can only manage your own courses.' }); return null; } return course; };
export const getCourses = async (req, res, next) => { try { const courses = await Course.find().populate('faculty', 'name email').sort({ createdAt: -1 }); res.json({ courses: await Promise.all(courses.map(counts)) }); } catch (error) { next(error); } };
export const getMyCourses = async (req, res, next) => { try { const courses = await Course.find({ faculty: req.user._id }).populate('faculty', 'name email').sort({ createdAt: -1 }); res.json({ courses: await Promise.all(courses.map(counts)) }); } catch (error) { next(error); } };
export const getCourse = async (req, res, next) => { try { if (!isValidId(req.params.id)) return invalidId(res, 'course'); const course = await Course.findById(req.params.id).populate('faculty', 'name email'); if (!course) return res.status(404).json({ message: 'Course not found.' }); const enrolled = req.user.role !== 'student' || Boolean(await Enrollment.exists({ student: req.user._id, course: course._id })); const modules = await Module.find({ course: course._id }).sort({ order: 1 }).lean(); const lectures = enrolled && modules.length ? await Lecture.find({ module: { $in: modules.map((item) => item._id) } }).sort({ order: 1 }).lean() : []; res.json({ course: { ...course.toObject(), enrolled, modules: modules.map((item) => ({ ...item, lectures: lectures.filter((lecture) => lecture.module.toString() === item._id.toString()) })) } }); } catch (error) { next(error); } };
export const createCourse = async (req, res, next) => { try { const { title, description, thumbnail } = req.body; if (!title || !description) return res.status(400).json({ message: 'Title and description are required.' }); const course = await Course.create({ title, description, thumbnail, faculty: req.user._id }); await course.populate('faculty', 'name email'); res.status(201).json({ course: await counts(course) }); } catch (error) { next(error); } };
export const updateCourse = async (req, res, next) => { try { const course = await owned(req.params.id, req.user._id, res); if (!course) return; const { title, description, thumbnail } = req.body; if (!title || !description) return res.status(400).json({ message: 'Title and description are required.' }); Object.assign(course, { title, description, thumbnail: thumbnail || '' }); await course.save(); await course.populate('faculty', 'name email'); res.json({ course: await counts(course) }); } catch (error) { next(error); } };
export const deleteCourse = async (req, res, next) => { try { const course = await owned(req.params.id, req.user._id, res); if (!course) return; const modules = await Module.find({ course: course._id }).select('_id'); const lectures = await Lecture.find({ module: { $in: modules.map((item) => item._id) } }).select('_id'); await Progress.deleteMany({ $or: [{ course: course._id }, { lecture: { $in: lectures.map((item) => item._id) } }] }); await Enrollment.deleteMany({ course: course._id }); await Lecture.deleteMany({ module: { $in: modules.map((item) => item._id) } }); await Module.deleteMany({ course: course._id }); await course.deleteOne(); res.json({ message: 'Course deleted.' }); } catch (error) { next(error); } };
